[package]
name = "permly"
version = "0.1.0"
authors = ["Xu Siyuan <inqb@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "permly"
test = false
bench = false
